defaults:
  snmp_version: "v2c" # or "v3"
  timeout_s: 2.5 # per request
  retries: 1 # retry only on timeouts
  target_budget_s: 10 # max total time per target
  oids:
    - "sysUpTime.0"
    - "sysName.0"

targets:
  - name: "B314_Switch_Dominic"
    ip: "172.16.0.240"
    community: "B314"
    oids:
    - "ifOperStatus.1"
    
  - name: "B314_Switch_LinnAmanda"
    ip: "172.16.0.253"
    community: "public"
    oids:
    - "sysName.0"
